### ISSUE TITLE
The code in returned Destination Entities is always Null

### ISSUE THREAD

**Issue by MrMustafa-2** [ICD-API/csharp-samples#6]
Hello, When I search as example for "blood", It return Destination Entities but not return the code, the code is always Null
I need to return the code value in the result, but it return Null
The code like:    3C0Y    or    MA12.0

**Comment by MrMustafa-2** [comment]
Any body here ,,,

**Comment by MrMustafa-2** [comment]
Where you Cann. I miss you :)

**Comment by mdonada** [comment]
Hi Mustafa,

The code is always null because you are using the Foundation search endpoint. The ICD-11 Foundation doesn't have codes.

For getting codes you have to use a linearization search endpoint, such as ICD-11 MMS

You'll find more info into our swagger page and in the API docs: https://icd.who.int/icdapi/docs2/APIDoc-Version2/

**Comment by MrMustafa-2** [comment]
Yes, Thank you :)
